### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by zoli456** [VaanaCZ/LANVP#1] opened 2021-05-14 10:01 UTC
If you are playing in other languages the item subtitles are flickering.

**Comment by VaanaCZ** [comment] 2021-05-15 23:32
I wasn't able to replicate the issue yet. 

I suspect this is caused due to the fact that internally, the game runs at double the reported framerate with every odd frame being used for rendering and every even "frame" being used for synchronization. 

The FPS unlocker completely removes the synchronization frames and makes every frame a rendering frame. Maybe the subtitles still rely on this fact and it causes them to flicker every other frame.

**Comment by zoli456** [comment] 2021-05-15 23:52
[https://www.youtube.com/watch?v=Gjfc7PJivGY](url)

**Comment by VaanaCZ** [comment] 2021-05-15 23:55
> https://www.youtube.com/watch?v=Gjfc7PJivGY

Thanks for providing the footage. Have you tried it with English subtitles as well?

**Comment by zoli456** [comment] 2021-05-16 00:03
This is the item subtitles not the voice subtitles. English language havent got it. (in this case the german replaced with hungarian)

**Comment by VaanaCZ** [comment] 2021-05-16 00:12
I can confirm that this issue happens when using the German language option. This doesn't happen with the English subs. Strange.

**Comment by VaanaCZ** [comment] 2021-05-16 11:24
Ok, I understand a bit better what is going on now. With "item subtitles" the game tries to draw a black rectangle behind the text, but something fails, causing it to be a different size every frame.

**Comment by VaanaCZ** [comment] 2021-05-16 13:17
I have identified the issue to be a bug with resolution enforcement. As a temporary fix, you can disable it.

1. Open the config file _lanvp.ini_ inside the game folder in notepad.
2. Scroll to the bottom and find the option `force_resolution`
3. Replace everything after the equals sign with a 0. It should look like this: `force_resolution=0`
4. Save the file and restart the game.

I will look for a better method of resolution enforcement a publish a fix in the next version.

**Comment by zoli456** [comment] 2021-05-16 16:46
Alright. Thank you for the help.

**Comment by VaanaCZ** [comment] 2021-07-04 17:37
The issue has been resolved in the latest release (v1.1).

**Closed by VaanaCZ** 2021-07-04 17:37 UTC
