### ISSUE TITLE
When launch getdfdijoystick monit appear

### ISSUE THREAD

**Issue by Tokwone** [VaanaCZ/LANVP#26] opened 2022-11-23 18:02 UTC
When launch getdfdijoystick monit appear, how to disable this monit?

**Comment by MrEWhite** [comment] 2023-04-01 21:55
I'm getting the same problem here. Upon launching the game on my Steam Deck, I get a pop up that says that. Clicking "Ok" lets the game launch as usual.

**Comment by f0li083** [comment] 2023-05-29 07:04
I get the same thing, clicking ok launches the game anyway.

**Comment by tiagogl** [comment] 2023-06-28 15:59
Same issue here on Batocera with Lutris

**Comment by VaanaCZ** [comment] 2024-04-12 11:32
Looks like Wine does not implement this function. Should be fixed in the next release.

**Comment by VaanaCZ** [comment] 2024-07-19 13:23
I do not use Linux or Wine, so someone else capable of producing a valid bug report has to do this. Either way, in the next version I am switching to Ultimate-ASI loader, so this should no longer be a problem.

**Comment by VaanaCZ** [comment] 2024-08-08 16:13
Fixed with the latest release:
https://github.com/VaanaCZ/LANVP/releases/tag/v2.0

**Closed by VaanaCZ** 2024-08-08 16:13 UTC

**Comment by Tiagoquix** [comment] 2024-08-08 23:20
Hello, I can confirm this is fixed. Many thanks for your support!
