### ISSUE TITLE
[V-Patch] error while generating config

### ISSUE THREAD

**Issue by ghost** [VaanaCZ/LANVP#19] opened 2022-06-30 18:56 UTC
Failed to create a new config. File handle invalid. Access is denied.

**Comment by VaanaCZ** [comment] 2022-06-30 19:43
I've had multiple people already report this issue, but I am not sure what causes it. I don't understand why V-Patch wouldn't have the permission to write files in the game directory.

My only guess is that somehow the working directory is not the same as the game directory. To test if that is the case, I compiled a special version of V-Patch, that prints out the current directory on startup. Could you try it and confirm that the path it prints is indeed the path to your game installation?

[LANVP_WorkingDirectoryTest.zip](https://github.com/VaanaCZ/LANVP/files/9022925/LANVP_WorkingDirectoryTest.zip)

**Comment by ante2103** [comment] 2022-06-30 20:15
![Desktop Screenshot 2022 06 30 - 22 13 35 22](https://user-images.githubusercontent.com/92825684/176770203-49b486c1-f7f7-4cd1-b90f-e19483c259e3.png)
![Desktop Screenshot 2022 06 30 - 22 13 39 85](https://user-images.githubusercontent.com/92825684/176770234-d39d964b-6bc0-4387-bac6-9ad8ba4a3173.png)

**Comment by VaanaCZ** [comment] 2022-06-30 21:01
I see now. The problem is that the game is located in Program Files, and so it cannot create the file, because Program Files is handled differently from the rest of the system, permission-wise.

Alright, I shall consider saving the config to a fallback location such as the user folder. For now, try to run the game in admin mode, or create the config file (lanvp.ini) manually.
[https://pastebin.com/xKUTxXe5](https://pastebin.com/xKUTxXe5)

**Comment by ante2103** [comment] 2022-07-01 07:45
Even after creating config file manually it still gives me error but it works fine in game with and without config anyways

**Comment by Bananaman** [comment] 2022-07-02 13:34
> Alright, I shall consider saving the config to a fallback location such as the user folder.

Hey. The best location would be the "userfolder/AppData/Roaming" folder. Its purpose is to store small, per-user config files.

You can get it via the Windows environment variable `APPDATA`.

There's also `ALLUSERSAPPDATA` which does it in a folder that all users have read-write access to (if I am not mistaken).

https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables

**Comment by antoniu200** [comment] 2022-09-15 19:34
> I see now. The problem is that the game is located in Program Files, and so it cannot create the file, because Program Files is handled differently from the rest of the system, permission-wise.

Can't the DLL request Administrator permissions once to create that config file?

The way I solved this issue was I simply took ownership of the folder (from Properties, Security, Advanced) and granted "Users" rights to edit.

**Comment by VaanaCZ** [comment] 2024-04-12 11:36
With the next release, the config will be shipped along with the patch, so this error should disappear.

**Comment by VaanaCZ** [comment] 2024-08-08 16:14
Fixed with the latest release:
https://github.com/VaanaCZ/LANVP/releases/tag/v2.0

**Closed by VaanaCZ** 2024-08-08 16:14 UTC
Labels: bug
